### ISSUE TITLE
你好，请问下Util.py文件里面的dll文件要怎么获取？

### ISSUE THREAD

**Issue by freedomofme** [YongGGe/PyMicroChat_master#1]

**Comment by ccpwcn** [comment]
同问
```
Traceback (most recent call last):
  File "E:/code/PycharmProjects/PyMicroChat_master/run.py", line 10, in <module>
    main()
  File "E:/code/PycharmProjects/PyMicroChat_master/run.py", line 6, in main
    client_tornado.start(usrname, passwd)
  File "E:\code\PycharmProjects\PyMicroChat_master\microchat\client_tornado.py", line 218, in start
    interface.init_all()
  File "E:\code\PycharmProjects\PyMicroChat_master\microchat\interface.py", line 219, in init_all
    if not Util.GenEcdhKey():
  File "E:\code\PycharmProjects\PyMicroChat_master\microchat\Util.py", line 184, in GenEcdhKey
    lib = loader("./microchat/dll/ecdh_x64.dll")
  File "c:\users\mslw_\appdata\local\programs\python\python36\Lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "c:\users\mslw_\appdata\local\programs\python\python36\Lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
```

**Comment by shuidixu** [comment]
查看不同的存储库
